
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/usr/share/cmake-4.2/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:14 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/home/gab/.config/Code/User/globalStorage/github.copilot-chat/debugCommand/"
      - "/home/gab/.config/Code/User/globalStorage/github.copilot-chat/copilotCli/"
      - "/home/gab/.local/bin/"
      - "/usr/local/sbin/"
      - "/usr/local/bin/"
      - "/usr/sbin/"
      - "/usr/bin/"
      - "/sbin/"
      - "/bin/"
      - "/usr/games/"
      - "/usr/local/games/"
      - "/snap/bin/"
    searched_directories:
      - "/home/gab/.config/Code/User/globalStorage/github.copilot-chat/debugCommand/uname"
      - "/home/gab/.config/Code/User/globalStorage/github.copilot-chat/copilotCli/uname"
      - "/home/gab/.local/bin/uname"
      - "/usr/local/sbin/uname"
      - "/usr/local/bin/uname"
      - "/usr/sbin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/home/gab/.config/Code/User/globalStorage/github.copilot-chat/debugCommand"
        - "/home/gab/.config/Code/User/globalStorage/github.copilot-chat/copilotCli"
        - "/home/gab/.local/bin"
        - "/usr/local/sbin"
        - "/usr/local/bin"
        - "/usr/sbin"
        - "/usr/bin"
        - "/sbin"
        - "/bin"
        - "/usr/games"
        - "/usr/local/games"
        - "/snap/bin"
...
