name: Windows standard tests
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
jobs:
   build-windows:
      runs-on: ${{ matrix.os }}
      strategy:
        fail-fast: false
        matrix:
          #build_type: ["Debug", "Release"]
          build_type: ["Debug"]
          #os: ["windows-2025", "windows-2022"]
          #static: ["TRUE","FALSE"]
          static: ["FALSE"]
          boost_version: [1.87.0]
          os: ["windows-2022"]
      steps:
      -  uses: actions/checkout@v6
      -  name: Set reusable strings
         # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
         id: strings
         shell: bash
         run: |
            echo "build-output-dir=${{ github.workspace }}\build" >> "$GITHUB_OUTPUT"
      -  name: download boost boost-msvc-14.3
         working-directory: ${{ steps.strings.outputs.build-output-dir }}
         shell: powershell
         run: |
            ${{ github.workspace }}\scripts\windows_download_boost.ps1 ${{ matrix.boost_version }} 14.3 64 "${{ steps.strings.outputs.build-output-dir }}"
      -  name: install boost
         id: install-boost
         shell: powershell
         working-directory: ${{ steps.strings.outputs.build-output-dir }}
         run: |
            $Process = Start-Process -Wait -FilePath "${{ steps.strings.outputs.build-output-dir }}\boost.exe" -Argumentlist @( "/VERYSILENT" , "/DIR=${{ steps.strings.outputs.build-output-dir }}/boost") -PassThru
            "boost-root=${{ steps.strings.outputs.build-output-dir }}/boost" >> $env:GITHUB_ENV
            exit $Process.ExitCode
      -  name: Configure
         working-directory: ${{ steps.strings.outputs.build-output-dir }}
         run: >
            cmake -A x64 -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DBOOST_ROOT=${{ steps.strings.outputs.build-output-dir }}/boost
            -DSTATIC_RUNTIME:BOOL=${{matrix.static}} -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/install
            -S ${{ github.workspace }} -B ${{ steps.strings.outputs.build-output-dir }} 
      -  name: Compile
         working-directory: ${{ steps.strings.outputs.build-output-dir }}
         run: >
            cmake --build ${{ steps.strings.outputs.build-output-dir }} --target install --config ${{ matrix.build_type }}
      -  name: Test
         run: |
            ctest -C ${{ matrix.build_type }}
         env:
            CTEST_OUTPUT_ON_FAILURE: 1
            VIRTUAL_ENV: VM
      -  name: Inspector
         run: ${{ github.workspace }}/install/lccinspector.exe
      -  name: On Failure print logs
         if: ${{ failure() }}
         run: |
           type $env:temp/open-license.log

 
