name: Windows standard tests
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
jobs:
   build-windows:
      runs-on: ${{ matrix.os }}
      strategy:
        fail-fast: false
        matrix:
          build_type: ["Release"]
          os: ["windows-2025"]
          static: ["TRUE"]
          boost_version: [1.90.0]

          #build_type: ["Debug", "Release"]
          #os: ["windows-2025", "windows-2022"]
          #static: ["FALSE"]
          #boost_version: [1.78.0,1.90.0]
      steps:
      -  uses: actions/checkout@v6
      -  name: Set reusable strings
         # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
         id: strings
         shell: bash
         run: |
            echo "build-output-dir=${{ github.workspace }}\build" >> "$GITHUB_OUTPUT"
      -  name: download boost boost-msvc-14.3
         working-directory: ${{ steps.strings.outputs.build-output-dir }}
         shell: powershell
         run: |
            ${{ github.workspace }}\scripts\windows_download_boost.ps1 ${{ matrix.boost_version }} 14.3 64 "${{ steps.strings.outputs.build-output-dir }}"
      -  name: install boost
         id: install-boost
         shell: powershell
         working-directory: ${{ steps.strings.outputs.build-output-dir }}
         run: |
            $Process = Start-Process -Wait -FilePath "${{ steps.strings.outputs.build-output-dir }}\boost.exe" -Argumentlist @( "/VERYSILENT" , "/DIR=${{ steps.strings.outputs.build-output-dir }}/boost") -PassThru
            "boost-root=${{ steps.strings.outputs.build-output-dir }}/boost" >> $env:GITHUB_ENV
            exit $Process.ExitCode
      -  name: Configure
         working-directory: ${{ steps.strings.outputs.build-output-dir }}
         run: >
            cmake -A x64 -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DBOOST_ROOT=${{ steps.strings.outputs.build-output-dir }}/boost
            -DSTATIC_RUNTIME:BOOL=${{matrix.static}} -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/install
            -S ${{ github.workspace }} -B ${{ steps.strings.outputs.build-output-dir }} -DUSE_OPENSSL=ON
      -  name: Compile
         working-directory: ${{ steps.strings.outputs.build-output-dir }}
         run: >
            cmake --build ${{ steps.strings.outputs.build-output-dir }} --target install --config ${{ matrix.build_type }}
      -  name: Test
         working-directory: ${{ steps.strings.outputs.build-output-dir }}
         run: |
            ctest -C ${{ matrix.build_type }} --test-dir ${{ steps.strings.outputs.build-output-dir }} --output-on-failure
         env:
            CTEST_OUTPUT_ON_FAILURE: 1
            VIRTUAL_ENV: VM
      -  name: license generator
         run: |
           dir ${{ github.workspace }}\install\bin
           ${{ github.workspace }}\install\bin\lccgen.exe project list

 
